version: '3'
services:
  postgres:
    image: postgres:13.2
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails_template
      - bundler_gems:/usr/local/bundle/
      - yarn_packages:/rails_template/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
volumes:
  postgres:
  bundler_gems:
  yarn_packages:
